[package]
name = "unipac"
version = "0.1.0"
authors = ["Yanderemine54 <ymtechnologies@mail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "~2.27.0", features = ["yaml"]}
ftp = "3.0.1"